name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:
  workflow_dispatch:

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.21'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: run unit tests
        run: make test
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.7.0
        with:
          skip-go-installation: true
          version: v1.55.2
